# Backend Build
FROM node:alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY ./packages/backend ./packages/backend
COPY ./packages/utils ./packages/utils

RUN npm install 

RUN npm run build 

CMD [ "npm", "run", "start", "--workspace=@engram-compose-template/backend" ]