# Frontend Build
FROM node:alpine as build

WORKDIR /usr/src/app

COPY package*.json ./
COPY ./packages/frontend ./packages/frontend
COPY ./packages/utils ./packages/utils

RUN npm install

RUN npm run build

# Frontend Nginx Proxy
FROM nginx:alpine

STOPSIGNAL SIGSTOP

COPY --from=build /usr/src/app/packages/frontend/public /etc/nginx/html
COPY ./packages/frontend/nginx/nginx.conf /etc/nginx/conf.d/default.conf
